// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrcMshrPlrrK_mgj71EqGwxE4_7WPyysw',
    appId: '1:451459709639:web:479590aad86170b3d41ce2',
    messagingSenderId: '451459709639',
    projectId: 'flutterfirebasenotificat-3ff47',
    authDomain: 'flutterfirebasenotificat-3ff47.firebaseapp.com',
    storageBucket: 'flutterfirebasenotificat-3ff47.firebasestorage.app',
    measurementId: 'G-4VSJ7J64P2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBf8BM2XQ_wkoQobIgzTTvLE6CBDEAEzME',
    appId: '1:451459709639:android:0800687a3d643130d41ce2',
    messagingSenderId: '451459709639',
    projectId: 'flutterfirebasenotificat-3ff47',
    storageBucket: 'flutterfirebasenotificat-3ff47.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWJHvC5J8M2gcHic8WkNM3VCDdK6kZT-E',
    appId: '1:451459709639:ios:1ae0a897b698b9edd41ce2',
    messagingSenderId: '451459709639',
    projectId: 'flutterfirebasenotificat-3ff47',
    storageBucket: 'flutterfirebasenotificat-3ff47.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseNotification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWJHvC5J8M2gcHic8WkNM3VCDdK6kZT-E',
    appId: '1:451459709639:ios:1ae0a897b698b9edd41ce2',
    messagingSenderId: '451459709639',
    projectId: 'flutterfirebasenotificat-3ff47',
    storageBucket: 'flutterfirebasenotificat-3ff47.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseNotification',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrcMshrPlrrK_mgj71EqGwxE4_7WPyysw',
    appId: '1:451459709639:web:dbd8f793964a4a9dd41ce2',
    messagingSenderId: '451459709639',
    projectId: 'flutterfirebasenotificat-3ff47',
    authDomain: 'flutterfirebasenotificat-3ff47.firebaseapp.com',
    storageBucket: 'flutterfirebasenotificat-3ff47.firebasestorage.app',
    measurementId: 'G-ESCLJWKZSL',
  );
}
